var countries = [
  { name: "Abkhazia", capital: "" },
  { name: "Afghanistan", capital: "" },
  { name: "Albania", capital: "" },
  { name: "Algeria", capital: "" },
  { name: "Andorra", capital: "" },
  { name: "Angola", capital: "" },
  { name: "Antigua and Barbuda", capital: "" },
  { name: "Argentina", capital: "" },
  { name: "Armenia", capital: "" },
  { name: "Australia", capital: "" },
  { name: "Austria", capital: "" },
  { name: "Azerbaijan", capital: "" },
  { name: "Bahamas", capital: "" },
  { name: "Bahrain", capital: "" },
  { name: "Bangladesh", capital: "" },
  { name: "Barbados", capital: "" },
  { name: "Belarus", capital: "" },
  { name: "Belgium", capital: "" },
  { name: "Belize", capital: "" },
  { name: "Benin", capital: "" },
  { name: "Bhutan", capital: "" },
  { name: "Bolivia", capital: "" },
  { name: "Bosnia and Herzegovina", capital: "" },
  { name: "Botswana", capital: "" },
  { name: "Brazil", capital: "" },
  { name: "Brunei", capital: "" },
  { name: "Bulgaria", capital: "" },
  { name: "Burkina Faso", capital: "" },
  { name: "Burundi", capital: "" },
  { name: "Cambodia", capital: "" },
  { name: "Cameroon", capital: "" },
  { name: "Canada", capital: "" },
  { name: "Cape Verde", capital: "" },
  { name: "Central African Republic", capital: "" },
  { name: "Chad", capital: "" },
  { name: "Chile", capital: "" },
  { name: "China", capital: "" },
  { name: "Colombia", capital: "" },
  { name: "Comoros", capital: "" },
  { name: "Congo-Brazzaville", capital: "" },
  { name: "Congo-Kinshasa", capital: "" },
  { name: "Cook Islands", capital: "" },
  { name: "Costa Rica", capital: "" },
  { name: "Croatia", capital: "" },
  { name: "Cuba", capital: "" },
  { name: "Cyprus", capital: "" },
  { name: "Czech Republic", capital: "" },
  { name: "Denmark", capital: "" },
  { name: "Djibouti", capital: "" },
  { name: "Dominica", capital: "" },
  { name: "Dominican Republic", capital: "" },
  { name: "East Timor", capital: "" },
  { name: "Ecuador", capital: "" },
  { name: "Egypt", capital: "" },
  { name: "El Salvador", capital: "" },
  { name: "Equatorial Guinea", capital: "" },
  { name: "Eritrea", capital: "" },
  { name: "Estonia", capital: "" },
  { name: "Ethiopia", capital: "" },
  { name: "Fiji", capital: "" },
  { name: "Finland", capital: "" },
  { name: "France", capital: "" },
  { name: "Gabon", capital: "" },
  { name: "Gambia", capital: "" },
  { name: "Georgia", capital: "" },
  { name: "Germany", capital: "" },
  { name: "Ghana", capital: "" },
  { name: "Greece", capital: "" },
  { name: "Grenada", capital: "" },
  { name: "Guatemala", capital: "" },
  { name: "Guinea", capital: "" },
  { name: "Guinea-Bissau", capital: "" },
  { name: "Guyana", capital: "" },
  { name: "Haiti", capital: "" },
  { name: "Honduras", capital: "" },
  { name: "Hungary", capital: "" },
  { name: "Iceland", capital: "" },
  { name: "India", capital: "" },
  { name: "Indonesia", capital: "" },
  { name: "Iran", capital: "" },
  { name: "Iraq", capital: "" },
  { name: "Ireland", capital: "" },
  { name: "Israel", capital: "" },
  { name: "Italy", capital: "" },
  { name: "Ivory Coast", capital: "" },
  { name: "Jamaica", capital: "" },
  { name: "Japan", capital: "" },
  { name: "Jordan", capital: "" },
  { name: "Kazakhstan", capital: "" },
  { name: "Kenya", capital: "" },
  { name: "Kiribati", capital: "" },
  { name: "Kosovo", capital: "" },
  { name: "Kuwait", capital: "" },
  { name: "Kyrgyzstan", capital: "" },
  { name: "Laos", capital: "" },
  { name: "Latvia", capital: "" },
  { name: "Lebanon", capital: "" },
  { name: "Lesotho", capital: "" },
  { name: "Liberia", capital: "" },
  { name: "Libya", capital: "" },
  { name: "Liechtenstein", capital: "" },
  { name: "Lithuania", capital: "" },
  { name: "Luxembourg", capital: "" },
  { name: "Macedonia", capital: "" },
  { name: "Madagascar", capital: "" },
  { name: "Malawi", capital: "" },
  { name: "Malaysia", capital: "" },
  { name: "Maldives", capital: "" },
  { name: "Mali", capital: "" },
  { name: "Malta", capital: "" },
  { name: "Marshall Islands", capital: "" },
  { name: "Mauritania", capital: "" },
  { name: "Mauritius", capital: "" },
  { name: "Mexico", capital: "" },
  { name: "Micronesia", capital: "" },
  { name: "Moldova", capital: "" },
  { name: "Monaco", capital: "" },
  { name: "Mongolia", capital: "" },
  { name: "Montenegro", capital: "" },
  { name: "Morocco", capital: "" },
  { name: "Mozambique", capital: "" },
  { name: "Myanmar", capital: "" },
  { name: "Nagorno-Karabakh", capital: "" },
  { name: "Namibia", capital: "" },
  { name: "Nauru", capital: "" },
  { name: "Nepal", capital: "" },
  { name: "Netherlands", capital: "" },
  { name: "New Zealand", capital: "" },
  { name: "Nicaragua", capital: "" },
  { name: "Niger", capital: "" },
  { name: "Nigeria", capital: "" },
  { name: "Niue", capital: "" },
  { name: "Northern Cyprus", capital: "" },
  { name: "North Korea", capital: "" },
  { name: "Norway", capital: "" },
  { name: "Oman", capital: "" },
  { name: "Pakistan", capital: "" },
  { name: "Palau", capital: "" },
  { name: "Palestine", capital: "" },
  { name: "Panama", capital: "" },
  { name: "Papua New Guinea", capital: "" },
  { name: "Paraguay", capital: "" },
  { name: "Peru", capital: "" },
  { name: "Philippines", capital: "" },
  { name: "Poland", capital: "" },
  { name: "Portugal", capital: "" },
  { name: "Qatar", capital: "" },
  { name: "South Korea", capital: "" },
  { name: "Romania", capital: "" },
  { name: "Russia", capital: "" },
  { name: "Rwanda", capital: "" },
  { name: "Sahrawi Republic", capital: "" },
  { name: "Saint Kitts and Nevis", capital: "" },
  { name: "Saint Lucia", capital: "" },
  { name: "Saint Vincent and the Grenadines", capital: "" },
  { name: "Samoa", capital: "" },
  { name: "San Marino", capital: "" },
  { name: "São Tomé and Príncipe", capital: "" },
  { name: "Saudi Arabia", capital: "" },
  { name: "Senegal", capital: "" },
  { name: "Serbia", capital: "" },
  { name: "Seychelles", capital: "" },
  { name: "Sierra Leone", capital: "" },
  { name: "Singapore", capital: "" },
  { name: "Slovakia", capital: "" },
  { name: "Slovenia", capital: "" },
  { name: "Solomon Islands", capital: "" },
  { name: "Somalia", capital: "" },
  { name: "Somaliland", capital: "" },
  { name: "South Africa", capital: "" },
  { name: "South Korea", capital: "" },
  { name: "South Ossetia", capital: "" },
  { name: "South Sudan", capital: "" },
  { name: "Spain", capital: "" },
  { name: "Sri Lanka", capital: "" },
  { name: "Sudan", capital: "" },
  { name: "Suriname", capital: "" },
  { name: "Swaziland", capital: "" },
  { name: "Sweden", capital: "" },
  { name: "Switzerland", capital: "" },
  { name: "Syria", capital: "" },
  { name: "Taiwan", capital: "" },
  { name: "Tajikistan", capital: "" },
  { name: "Tanzania", capital: "" },
  { name: "Thailand", capital: "" },
  { name: "Togo", capital: "" },
  { name: "Tonga", capital: "" },
  { name: "Transnistria", capital: "" },
  { name: "Trinidad and Tobago", capital: "" },
  { name: "Tunisia", capital: "" },
  { name: "Turkey", capital: "" },
  { name: "Turkmenistan", capital: "" },
  { name: "Tuvalu", capital: "" },
  { name: "Uganda", capital: "" },
  { name: "Ukraine", capital: "" },
  { name: "United Arab Emirates", capital: "" },
  { name: "United Kingdom", capital: "" },
  { name: "United States", capital: "" },
  { name: "Uruguay", capital: "" },
  { name: "Uzbekistan", capital: "" },
  { name: "Vanuatu", capital: "" },
  { name: "Vatican City", capital: "" },
  { name: "Venezuela", capital: "" },
  { name: "Vietnam", capital: "" },
  { name: "Yemen", capital: "" },
  { name: "Zambia", capital: "" },
  { name: "Zimbabwe", capital: "" }
]
window.onload = function(){
  l = document.getElementById("country").innerHTML = countries[4].name;
}
